version: '3'
services:
  java-application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
  mysql-db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solenix
      MYSQL_USER: root
      MYSQL_PASSWORD: root